name: Code Style Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: read
  security-events: write

jobs:
  pylint-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - uses: Gr1N/setup-poetry@v8

    - working-directory: src/api
      run: poetry install --with dev

    - uses: pr-annotators/pylint-pr-annotator@main

    - working-directory: src/api
      run: poetry run pylint **/*.py --rcfile ../../pylintrc
