name: Code Style Checking

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r weckpi-core/requirements.txt
        pip install -r weckpi-core/requirements.dev.txt

    - name: Set up pylint annotator
      uses: pr-annotators/pylint-pr-annotator@main

    - name: Analyse the code with pylint
      run: |
        pylint weckpi-core/*.py

  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

#      - name: Install dependencies
#        working-directory: weckpi-web/src
#        run: |
#          yarn install --dev
#          yarn add @microsoft/eslint-formatter-sarif@2.1.7
#
#      - name: Analyse the code with ESLint
#        working-directory: weckpi-web/src
#        run: yarn eslint
#          --config .eslintrc.json
#          --ext .js,.jsx,.ts,.tsx
#          --format @microsoft/eslint-formatter-sarif
#          --output-file eslint-results.sarif
#        continue-on-error: true
#
#      - name: Upload analysis results to GitHub
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: weckpi-web/src/eslint-results.sarif
#          wait-for-processing: true
